config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # READ ALL
  # get 'tasks', to: 'tasks#index'

  # CREATE
  # get 'tasks/new', to: 'tasks#new', as: :new
  # post 'tasks', to: 'tasks#create', as: :create

  # READ ONE'
  # get 'tasks/:id', to: 'tasks#show', as: :task

  # UPDATE
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch 'tasks/:id', to: 'tasks#update', as: :update

  # DELETE
  # 'tasks/:id', to: 'tasks#destroy', as: :destroy

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def new
    @task = Task.new
  end

  def index
    @tasks = Task.all
  end

  def show; end

  def edit; end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path(@task)
  end

  def update
    @task.update(task_params)

    redirect_to tasks_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks:</h1>

<% @tasks.each do |task| %>
  <% if task.completed == true %>
    <input type="checkbox" checked><%= link_to task.title, task_path(task) %><br> <%= link_to 'Delete this task', destroy_path(task), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% elsif %>
    <input type="checkbox"><%= link_to task.title, task_path(task) %><br> <%= link_to 'Delete this task', destroy_path(task), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
<% end %>

<footer><%= link_to "+ Add new task", new_path %></footer>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<%= link_to "Edit this task", edit_task_path %>


<% if @task.completed == true %>
  <input type="checkbox" checked>This task is completed.<br>
<% elsif %>
  <input type="checkbox">This task has not been completed so far.<br>
<% end %>


<footer><%= link_to "Back to list", tasks_path %></footer>